- doc/src/Container.md
- docker/Dockerfile-CLI
- docker/Dockerfile-Jupyter
- karabo/util/jupyter.py
Adds a function to fix the data directory not being used inside of the jupyter notebook.
There is also documentation on this in the container.md.
Also updates the container builds to reflect the general installation process of karabo now.
> Jupyter Notebook having issues with data directory workaround

- conda/meta.yaml
- requirements.txt
added pinocchio
removed requirements 
tu es
> added pinocchio

- environment-dev.yaml
> Modified emv yaml with correct xarray version.

- karabo/__init__.py
- karabo/examples/how_to_use_karabo_example.ipynb
```
from karabo.util.jupyter import set_rascil_data_directory_env
set_rascil_data_directory_env()
```
Was added to karabo/__init__.py
> Added set_rascil_data_directory_env to karabo init.

- karabo/test/test_source_detection.py
- karabo/util/math_util.py
seed 42 works for the current parameter configurations of `test_source_detection.py` `test_create_detection_from_ms_small`
Closes #187
> bugfix set seed to test_create_detection_from_ms_small

- karabo/simulation/telescope.py
- karabo/test/test_telescope_baselines.py
Addressing the baseline-based filtration for the stations of the telescope. Both lower and upper cut-off on the baseline is implementation.
> Adding functionality for baseline length based in the telescope module.

- karabo/test/test_source_detection.py
- karabo/warning.py
- Removed test which needs more investigation why it fails.
> Commented out test which needs more investigation.

- karabo/__init__.py
- @Lukas113 added the automatically setting of `LD_LIBRARY_PATH` in WSL
> Added automatical setting of `LD_LIBRARY_PATH` in WSL

- doc/src/development.md
> updated cscs object storage upload in developers documentation

- environment-dev.yaml
- karabo/__init__.py
- karabo/simulation/observation.py
- karabo/test/test_simulation.py
- karabo/util/gpu_util.py
- Added GPU support for Oskar by building Oskar with GPU support
- Fixed error with environment variables on WSL
- Bumped oskar to 2.8.3
> Vt 180 gpu acceleration in oskar

- karabo/simulation/observation.py
- karabo/test/test_simulation.py
- Changed test to automatically decide if it should use CPU or GPU
- Updated logic by only deciding what to use when use_gpu is set to None.
> Updated logic on GPU usage if use_gpu is set to None.

- README.md
- doc/src/installation_user.md
Added system requirements
The docs need to be rebuild for this :)
> #204 added system requirements and fixed some typos

- .github/workflows/nightly-build.yml
- .github/workflows/test-nightly.yaml
- Merging this to be able to trigger this on github.
> Vt 239 karabo package for users is tested

- karabo/sourcedetection/result.py
- karabo/util/data_util.py
Implemented #207 and added/improved type annotations in `result.py` and `data_util.py`.
closes #207
> Lg 203 address unige report

- README.md
- doc/src/installation_user.md
- docker/Dockerfile-CLI
- docker/Dockerfile-Jupyter
- added the cuda-channel to the docker images
- updated description on installation
> Updated cuda definitions and usage

- .github/workflows/conda-build.yml
- .github/workflows/test-nightly.yaml
- Fixed priority channels in nightly test
> Added i4ds to the front of the channel queues.

- karabo/examples/source_detection_assessment.ipynb
> Fixed notebook

- karabo/test/test_pinocchio.py
> decreased memory size of the test

- karabo/simulation/observation.py
- karabo/test/test_long_observation.py
Also, the number of observatinal hour is reduced from 12 to 4 based on SKADC-3 requirement.
> Bug Fix: Default parameters changed for Long Observations

- .pre-commit-config.yaml
- karabo/imaging/imager.py
- karabo/simulation/observation.py
- karabo/simulation/pinocchio.py
- karabo/test/test_pinocchio.py
- karabo/tools/observation_planner.py
- karabo/util/FileHandle.py
- karabo/util/hdf5_util.py
- requirements.txt
major mypy upgrade and minor black upgrade
> Lg 330 enhance pre commit hooks

- conda/meta.yaml
- environment-dev.yaml
integration of [tools21cm](https://github.com/sambit-giri/tools21cm) into Karabo.
> added tools21cm to user- and dev yaml

- .github/workflows/dev-workflow.yaml
this is just a sample workflow on the default branch so that everyone is able to try out their own workflow
> added dev-workflow [skip ci]

- .github/workflows/dev-workflow.yaml
added template of dev-workflow
> template dev-workflow [skip ci]

- .github/workflows/build-dev-docker-image.yaml
add build-dev-docker-image to default branch for repository-dispatch reasons
> add build-dev-docker-image to default branch [skip ci]

- .github/workflows/build-dev-docker-image.yaml
- .github/workflows/purge-image.yml
for availability in other branches
> added purge-image to default branch [skip ci]

- environment-dev.yaml
- karabo/imaging/imager.py
tests should fail because we still have legacy test-setup which is using RASCIL 0.7.0 but here we have RASCIL 1.0.0
> Fs rascil 1 0 0 integration

- karabo/data/external_data.py
- karabo/imaging/image.py
- karabo/karabo_resource.py
- karabo/util/FileHandle.py
- karabo/util/data_util.py
- karabo/util/jupyter.py
- karabo/util/my_types.py
- requirements.txt
> Formatting1

- environment.yaml
- requirements.txt
Closes #411  . This changes shouldn't change the current virtual environment. It jus includes all direct dependencies of Karabo into the environment.yaml.
> updated direct karabo-deps

- .gitignore
- doc/src/examples/example_structure.md
- karabo/imaging/imager.py
- karabo/test/test_beam_ska-low.py
- karabo/test/test_dask.py
- karabo/util/dask.py
- karabo/util/data_util.py
- Improves Dask by supporting Nanny (workers are restarted when they die, thus no more stuck job).
- Updated documentation on dask
- Added unique path usage for the Imager because of Parallelization
- Added dask tests
- Removed unused öqtplotlib statement in a test
> Vt dask 2 dot 0 and fixes

- karabo/test/test_dask.py
- simple single core test for dask
> Simple dask test for local cluster and single node

- docker/user/Dockerfile
fixed [Build User Image](https://github.com/i4Ds/Karabo-Pipeline/actions/runs/5465772231) (i think).
> added shared library libarchive13 to user Dockerfile

- karabo/karabo_resource.py
> minor bugfix of CaptureSpam

- doc/src/development.md
- doc/src/installation_user.md
I recently went through installing the pipeline, both via `Docker` and via the developer installation. This PR has updated commands, versions and references that I noticed were not up-to-date during the installations.
> Improve installation docs for user and develop configurations

- karabo/data/external_data.py
- karabo/simulation/signal/helpers.py
- karabo/simulation/signal/seg_u_net_segmentation.py
- karabo/simulation/signal/signal_21_cm.py
- karabo/simulation/signal/synchroton_signal.py
- karabo/test/test_superimpose.py
runned `black .` on repo to pass ci-tests.
> reformatted repo :arrow_lower_left:

- .github/workflows/build-docker-image.yml
- Dockerfile
bugfix: enable docker-builds on release-event on ci
> bugfix added release-event to valid docker-build ci :heartbeat:

- karabo/data/external_data.py
closes #561 
Addresses all points mentioned in the issue.
> 561 download object

- conda/meta.yaml
- environment.yaml
upper bound numpy because of #584
> Upper bound numpy

- karabo/imaging/image.py
- karabo/simulation/beam.py
- karabo/simulation/signal/plotting.py
- karabo/sourcedetection/evaluation.py
mypy updated their type-hints which lead to mypy breaking changes (not API).
Our CI-tests were failing due to this issue and this stopped other PR to be accepted.
> addressed mypy issues due to matplotlib update :clock430:

- doc/src/development.md
- doc/src/examples/example_structure.md
- doc/src/examples/examples.md
- karabo/data/external_data.py
Fixes issues that popped up during https://jira.skatelescope.org/browse/CHOC-21
> Download timeout, improved docs

- karabo/data/obscore.py
- karabo/data/src.py
- karabo/examples/SRCNet_rucio_meta.py
- karabo/simulation/interferometer.py
- karabo/test/test_obscore.py
Bugfix `RucioMeta` serialization.
> Fix rucio serialization

- karabo/examples/SRCNet_workflow_AAstar.py
- karabo/test/test_utils.py
- karabo/util/_types.py
- karabo/util/helpers.py
- Adds SRCNet workflow execution file to examples with env-var configurability (see Jira CHOC-185).
- Adds `Environment` class to enable easy env-var parsing.
> Workflow execution script
