i4Ds/Karabo-Pipeline

- README.md
- doc/src/Installation.md
Generally the issues have been fixed with updates to the repositories i4ds/bdsf-build and i4ds/rascil-build. 
The bdsf build has been updates so that the import error on importing `from rascil.apps import rascil_imager` no longer fails.
The issue lied in the aotools package, which downgraded upon installation the numpy installation, which then had issues, as the bdsf was installed against a certain numpy instance with boost-numpy. 
Now the bdsf package has different versions for different numpy versions. 
The rascil imager is now running again on python 3.8 (generally python 3.8 is the version we use now)
@Lukas113 please test this.
> Fix Installation Issues with RASCIL and BDSF

- .github/workflows/build-docs.yaml
The action now deletes previous folders so that the error of folders already existing goes away.
> fix doc creation

- .github/workflows/build-cli-docker-image.yml
- .github/workflows/build-jupyter-docker-image.yml
- The docker images are now build with the released versions of conda (hopefully, this is hard to test).
> Updated that the docker images are build only after conda build is finished.

- .github/workflows/conda-build.yml
- conda/meta.yaml
- environment-dev.yaml
- to give a cuda-toolkit version, you cannot do cuda-toolkit=11.7.0 but you need to do it as follows: `conda install -c "nvidia/label/cuda-11.7.0" cuda-toolkit`
- Fixed astropy to a version because 5.2 seems broken.
- Rebuilt oskar without numpy fixing because this caused errors when updating oskar to 2.8.3.
> Oskarpy 2.8.3 works again

- conda/meta.yaml
- environment-dev.yaml
- Replaced cuda-toolkit with two cuda libaries by trial & error.
> Vt 235 cuda runtime dependencies are slimmed down

- .gitignore
- README.md
- doc/src/installation_user.md
This should fix #283, #287 and #294
Installation was tested on CSCS and local system. Shortcomings: Does not document installation with a pre-existing Conda installation, and/or possibly with different python versions.
> Simplification of User installation manual

- conda/meta.yaml
- environment.yaml
fixed version from `0.0.11` to `0.3.0` because it was not wrongly referenced.
> fixed version nifty-gridder

- karabo/imaging/image.py
- karabo/simulation/interferometer.py
- karabo/simulation/sky_model.py
- karabo/simulation/visibility.py
- karabo/test/test_skymodel.py
- karabo/test/test_spectral_line.py
- karabo/util/data_util.py
- karabo/util/hdf5_util.py
- karabo/util/math_util.py
- karabo/util/my_types.py
- karabo/util/plotting_util.py
Part of #304 
- Introduced some number-like types in my_types.py to handle number-like types and numpy broadcasting to some extend
- The following files are now mypy --strict: hdf5_util.py, math_util.py, sky_model.py, visibility.py
- Moved `simulate_foreground_vis` from visibility.py to interferometer.py to avoid cyclic dependency
- Made deep-copies of all filter-functions of `SkyModel` to be consistent. Before we copied and returned just `filter_by_raidus` but not `filter_by_flux` and `filter_by_frequency`
- Removed `nside` from `SkyModel` constructor because it did nothing. But maybe it was meant to do something, but I couldn't figure that out.
- `SkyModel` `shape` and `num_sources` are now properties instead of updating them each time we change something in`source`.
- Other minor …
> Lg 304 codestyle1

- karabo/simulation/interferometer.py
We found that Oskar expects the Gaussian beam FWHM to be in field pattern. Now the option to input it in power pattern is added together with the respective conversion.
> Add the option to input the Gaussian beam FWHM in power pattern

- karabo/simulation/interferometer.py
- karabo/simulation/observation.py
- karabo/test/test_observation.py
- karabo/test/test_simulation.py
- karabo/warning.py
- Implements/fixes parallelization by observation in Oskar
- Adds some tests for it.
- Removes some code and if/else statements in run_simulation and rather processes them in a different spot, if needed.
- Removes parallelization by sky-chunk because currently no method to combine the visibilities exists, which is tested for correctness.
> Vt 393 parallelization of oskar fix

- karabo/karabo_resource.py
Added CaptureSpam to karabo_resource.py to be able to capture third-party library spam-messages.
Should be good enough. I tested it with all print-options (not logging). The only drawback is, that it can only check for each new-line if it has already been printed. So if e.g. a third-party library wraps their output in something like "--------------------\n" multiple times, it gets captured after the first time. It's also not able to capture with regex, just exact-match. But for the second case, CaptureSpam could be extended to support capturing by regex (I think).
> added CaptureSpam to KaraboResource

- docker/user/Dockerfile
There was an issue using all our [docker-images](https://github.com/i4ds/Karabo-Pipeline/pkgs/container/karabo-pipeline) up until version `0.18.0`. `run_simulation` failed, where OSKAR python bindings claimed, that OSKAR library was not found (see image blow). This is essentially not true. They just failed an import of a sub-dependency. The issue was, that they captured their import error in `settings_tree.py`:
```python
try:
from . import _settings_lib
from . import _apps_lib
except ImportError:
_settings_lib = None
_apps_lib = None
```
There they try to import `_settings_lib.cpython-39-x86_64-linux-gnu.so` and `_apps_lib.cpython-39-x86_64-linux-gnu.so` which are their own .so files available in the oskar package location. The main issue is, that there they point to the exact …
> fixed OSKAR library not found in Dockerfile

- karabo/simulation/line_emission.py
- karabo/test/test_line_emission.py
- karabo/util/_types.py
The test function now has `assert` statements to check the intermediate files from the line emission pointing, as well as the final results from the beam correction.
The code was checked using the precommit hooks in the repo, but let me know if there are any additional formatting checks that should happen.
> Improve line emission end-to-end test with golden files

- karabo/simulation/pinocchio.py
- karabo/test/pinocchio_params.txt
- karabo/test/test_pinocchio.py
This PR adds `assert` statements to the PINOCCHIO test, and introduces a sample parameter file to be used by the test.
Also, it removes the `getSkyModel` functions from the `PINOCCHIO` class, which were incorrectly assuming that dark matter halos can be used as HI source objects.
Closes #325
Closes #473
> Improve PINOCCHIO test and remove unnecessary feature

- doc/src/development.md
- doc/src/installation_user.md
closes #550 
Hotfix to link shared libraries like cuda in `/usr/lib/wsl/lib`. Properly linking using `ldconfig` doesn't work, because NVIDIA doesn't  install `libcuda.so.1` as a symlink (see https://forums.developer.nvidia.com/t/wsl2-libcuda-so-and-libcuda-so-1-should-be-symlink/236301)
> fixed install commands doc for WSL2

- conda/meta.yaml
- environment.yaml
The wsclean conda package is currently not installed when installing the current karabo-pipeline released. This PR should fix this.
> Added wsclean dependency to meta.yaml

- karabo/simulation/sky_model.py
When exporting a sky model to csv file via `save_sky_model_as_csv()` the object id was written into the wrong column (`observed redshift` instead of `source id (object)`. This PR fixes this.
> Object id exported to wrong column name

- conda/meta.yaml
- environment.yaml
Fixes current failing tests due to a bug of `setuptools` regarding `importlib_metadata`.
> exclude buggy setuptools version :collision:

- karabo/simulation/telescope.py
- karabo/test/test_filehandler.py
- karabo/test/test_telescope.py
- karabo/util/_types.py
- karabo/util/file_handler.py
Telescope configuration can now be saved without raising an exception. However, an exception is raised in case the folder exists.
> Fix issue #580

- .github/workflows/build-docs.yml
- .github/workflows/test-user-package.yml
- .github/workflows/test.yml
Due to changes to the `conda-incubator/setup-miniconda` workflow running the actions `test` and `build-docks` failed. This PR fixes the issue by updating our actions to `conda-incubator/setup-miniconda@v3`.
| Action   | Updated? | Tested? | Comment |
|----------|------------|--------|--------|
| Tests | yes | yes |
| Build Docs | yes | yes |
| Test User Package | yes | no | I didn't dare to test |
| Build Docker Image | no | no | Doesn't use setup-miniconda |
| Conda Build | no | no | Doesn't use setup-miniconda |
| Dev Workflow | no | no | Doesn't use setup-miniconda |
| pages-build-deployment | no | yes | Successful run after 'Build Docs' |
> Fix GitHub actions

- doc/src/development.md
- doc/src/index.rst
- doc/src/installation_user.md
- doc/src/main_features/simulation.rst
- doc/src/utilities/utils.rst
- karabo/imaging/imager_wsclean.py
- karabo/simulation/east_north_coordinate.py
- karabo/simulation/interferometer.py
- karabo/simulation/line_emission.py
- karabo/simulation/line_emission_helpers.py
- karabo/simulation/observation.py
- karabo/simulation/sky_model.py
- karabo/sourcedetection/evaluation.py
- karabo/sourcedetection/result.py
- karabo/util/data_util.py
- karabo/util/file_handler.py
- karabo/util/hdf5_util.py
- karabo/util/helpers.py
- karabo/util/math_util.py
- karabo/util/rascil_util.py
As we seem to be working towards a Karabo version 1.0 I'm about to update the documentation.
What I did so far:
* Add documentation to many modules in _karabo.util_ package
* Rewriting of many docstring to the Google format.
> Updating Documentation

- .github/workflows/update-citation-cff.yml
- CITATION.cff
I added a citation file as described here: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
This commit resolves issue #640.
> Added citation file

- .github/workflows/build-docs.yml
The action `actions/upload-artifact` required an updated from v3 -> v4, because v3 is depricated since Jan 30, 2025. There is no transition period. Hence, the workflow fails. This was fixed in this PR.
> Workflow Update

- karabo/data/obscore.py
- karabo/simulation/telescope.py
- karabo/test/test_obscore.py
- karabo/test/test_telescope.py
- karabo/test/test_telescope_baselines.py
This is a draft to show my progress towards SP-5327 - Improve discoverability of MWA data via TAP/Rucio.
So far I've only completed part of choc-232:
- fixed angular resolution calculation for s_resolution
- swap em_min and em_max
- fix calculation of t_xel, number of timesteps
at this point the tests pass, but I noticed an issue with one of the test datasets, and will check with the team what to do about it.
after that I intend to extend the tests to MWA flavoured measurement sets, uvfits, uvh5.
> SP-5327/CHOC-232 MWA ObsCore metadata improvements

- .github/workflows/test.yml
- conda/meta.yaml
- environment.yaml
- karabo/data/obscore.py
- karabo/simulation/interferometer.py
- karabo/simulation/visibility.py
- karabo/test/conftest.py
- karabo/test/test_notebooks.py
- karabo/test/test_obscore.py
- add pyuvdata 2.4.1 as a dependency. currently pinned because for python 3.9 compatibility
- use pyuvdata for ms and uvfits reading
- add small test datasets for mwa ms and uvfits, uploaded to CSCS as test fixtures
- use future array shapes in pyuvdata
- auto-format fixes
> [choc-233,234] add MWA uvfits obscore support via pyuvdata
